name: Continuous Deployment

on:
  push:
    branches:
      - master
      - develop

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      SOURCE_DIR: "build/"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Deploy staging
        run: |
            printenv
        env:
          AWS_S3_BUCKET: ${{ secrets.STAGING_AWS_S3_BUCKET }}

      - name: Deploy production
        run: |
            printenv
        env:
          AWS_S3_BUCKET: ${{ secrets.PRODUCTION_AWS_S3_BUCKET }}
